### ISSUE TITLE
Get Card Details by bitcoin address

### ISSUE THREAD

**Issue by naps62** [bitreserve/api#13]
It seems [this endpoint](https://developer.bitreserve.org/api/v0/#get-card-details) accepts not only a card id, but also a bitcoin address id. I tested it with the following values:

* `1LbHhVFjLeC3hVhW4FXrwu7MNUCkoGTwA5`
* `2daa59e8-89c5-4cbe-99fc-f66435024bcf`

And for both of them I get the same result:

```ruby
@address={"bitcoin"=>"1LbHhVFjLeC3hVhW4FXrwu7MNUCkoGTwA5"},
 @addresses=[{"id"=>"1LbHhVFjLeC3hVhW4FXrwu7MNUCkoGTwA5", "network"=>"bitcoin"}],
 @available="0.001",
 @balance="0.001",
 @currency="XAU",
 @id="2daa59e8-89c5-4cbe-99fc-f66435024bcf",
 @label="XAU card",
 @last_transaction_at="2014-12-02T00:29:45.507Z",
 @position=7>
```

I realize this is probably intended, but shouldn't it be documented as well?

**Comment by ruimarinho** [comment]
@naps62 thanks for the report. We've submitted a PR to add a clarification about the card lookup flexibility.
