### ISSUE TITLE
Card settings vs position

### ISSUE THREAD

**Issue by naps62** [bitreserve/api#20]
The documents state that a card entity has a `position` attribute. But instead, the current JSON I'm getting has a `settings` attribute, which in turn has `position` and `starred`

Which one of these is the correct one?

**Comment by jrpereira** [comment]
The `position` is within the `settings` attribute, it's a documentation mismatch, needs to be corrected.

Feel free to send a PR to fix any documentation issues you find or if you have any suggestions for clarity!

**Comment by naps62** [comment]
Sure, I can do that. I just had to be sure of which was the outdated one, the docs or the API

**Comment by nunorafaelrocha** [comment]
I've just send a PR to fix the documentation about this issue.
