### ISSUE TITLE
Public Transactions API

### ISSUE THREAD

**Issue by naps62** [bitreserve/api#21]
The returned information for transactions doesn't match the entity description. And even between different methods for getting transaction(s), the values are slightly different

* **List Card Transactions** Doesn't have `type`
* **Get All Transactions (Public)** has a `quotedAt` which I don't see documented anywhere (what is it?)  and doesn't have `type`
* **Get Transaction (Public)** I would assume it returned the same values as the one above, but it doesn't look like it, from the docs

There are possibly other cases I didn't check (like Create Transaction)
I also didn't check if the actual returned JSON has the same inconsistencies. This was just by looking at the docs

I also understand that some of these values might not make sense under the context of certain endpoints, which is OK, but it doesn't look like that's the case for all of them

**Comment by jrpereira** [comment]
@naps62, good catches. We'll look into it and update here once it's solved. It's possible some of it are documentation inconsistencies.
